### ISSUE TITLE
Compile ucrdtw for Windows?

### ISSUE THREAD

**Issue by apiszcz** [klon/ucrdtw#4]
Has anyone built this library on Windows 7, 64bit O/S?
The output from python setup.py build follows:
# 

C:\Users\p\Downloads\ucrdtw-master>python setup.py build
running build
running build_ext
No module named msvccompiler in numpy.distutils; trying from distutils
building '_ucrdtw' extension
C:\Users\p\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\Python27\PC /Tcsrc/_ucrdtw.c /Fobuild\temp.
win-amd64-2.7\Release\src/_ucrdtw.obj
Found executable C:\Users\p\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe
_ucrdtw.c
c:\python27\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
src/_ucrdtw.c(73) : error C2275: 'PyObject' : illegal use of this type as an expression
        c:\python27\include\object.h(108) : see declaration of 'PyObject'
src/_ucrdtw.c(73) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(74) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(74) : warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
src/_ucrdtw.c(75) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(75) : warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
src/_ucrdtw.c(75) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(75) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(75) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(81) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(81) : warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
src/_ucrdtw.c(81) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(81) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(81) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(85) : error C2275: 'PyObject' : illegal use of this type as an expression
        c:\python27\include\object.h(108) : see declaration of 'PyObject'
src/_ucrdtw.c(85) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(86) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(86) : warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
src/_ucrdtw.c(87) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(87) : warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
src/_ucrdtw.c(87) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(87) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(87) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(88) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(88) : warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
src/_ucrdtw.c(88) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(88) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(88) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(94) : error C2143: syntax error : missing ';' before 'type'
src/_ucrdtw.c(95) : error C2143: syntax error : missing ';' before 'type'
src/_ucrdtw.c(97) : error C2143: syntax error : missing ';' before 'type'
src/_ucrdtw.c(98) : error C2143: syntax error : missing ';' before 'type'
src/_ucrdtw.c(100) : error C2143: syntax error : missing ';' before 'type'
src/_ucrdtw.c(103) : error C2143: syntax error : missing ';' before 'type'
src/_ucrdtw.c(104) : error C2143: syntax error : missing ';' before 'type'
src/_ucrdtw.c(105) : error C2143: syntax error : missing ';' before 'type'
src/_ucrdtw.c(108) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(108) : warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
src/_ucrdtw.c(108) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(108) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(108) : error C2065: 'data_array' : undeclared identifier
src/_ucrdtw.c(109) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(109) : warning C4047: '==' : 'int' differs in levels of indirection from 'void *'
src/_ucrdtw.c(109) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(109) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(109) : error C2065: 'query_array' : undeclared identifier
src/_ucrdtw.c(111) : error C2065: 'status' : undeclared identifier
src/_ucrdtw.c(117) : error C2275: 'PyObject' : illegal use of this type as an expression
        c:\python27\include\object.h(108) : see declaration of 'PyObject'
src/_ucrdtw.c(117) : error C2065: 'ret' : undeclared identifier
src/_ucrdtw.c(117) : error C2065: 'location' : undeclared identifier
src/_ucrdtw.c(117) : error C2065: 'distance' : undeclared identifier
src/_ucrdtw.c(118) : error C2065: 'ret' : undeclared identifier
src/_ucrdtw.c(118) : warning C4047: 'return' : 'PyObject *' differs in levels of indirection from 'int'
error: Command "C:\Users\p\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\lib\site-packages\numpy\core\include -IC:\Python27\include -IC:\Python27\PC /Tcsrc/_ucrdtw.
c /Fobuild\temp.win-amd64-2.7\Release\src/_ucrdtw.obj" failed with exit status 2

**Comment by klon** [comment]
I am sorry, I currently have no Windows machine to try this on.
