### ISSUE TITLE
Cannot import _ucrdtw

### ISSUE THREAD

**Issue by msegala** [klon/ucrdtw#5]
Thanks for the great code!
I built the package by running 'make' at the top level and it seems to of worked. 
However, I now try

> > > import _ucrdtw
> > > and get the error
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named _ucrdtw

Any ideas?

**Comment by alexZ82** [comment]
Did you resolve this?

**Comment by alexZ82** [comment]
So to answer my own question, you have to build the setup. Under python3:
python3 setup.py build
python3 setup.py install
